### ISSUE TITLE
Allow user to cancel order/ navigate back to restaurant page 

### ISSUE THREAD

**Issue by nicolej2122** [Team-APPetite/FoodStack#20]
Add an option for the user to cancel their order or navigate back to the restaurant menu if they are the only user in the order

**Comment by ckcherry23** [comment]
How is this different from the cancel order feature?

**Comment by nicolej2122** [comment]
Users who choose to wait 0 minutes for others to join don't have the option to cancel their order. So I think that should be added.

**Comment by ckcherry23** [comment]
When there is only 1 user
